#Include "PROTHEUS.CH"
#Include "RWMAKE.CH"
#Include "TOPCONN.CH"

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPrograma  ³ M410PVNF ºAutor  ³ Luciano            º Data ³  16/12/2024 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDesc.     ³ Executado antes da rotina de geração de NF's (MA410PVNFS()).±±
±± Ao chamar a rotina Preparar Documento de Saída "Prep.Doc.Saída"         ±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±
±±ºUso       ³ Preenche a carga do pedido na SC9 C9_CARGA para ser usado  ±±
±±È            para ser usado do faturamento por Carga. 	              ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/

User Function M410PVNF

Local lRet := .T.
Local cTexto := ""

//ApMsgInfo("passou aqui M410PVNF pedido " + SC5->C5_NUM ,"M410PVNF()")
lRet := U_BLOQ_FAT(SC5->C5_NUM)

nRetSQL := 0

If !(SC9->(FieldPos("C9_CARGA")) > 0 ) //se nao existir
     cTexto += "O campo C9_CARGA não existe na base. Acionar Suporte." + CHR(13)
	 //cTexto += "O processo não será concluído." + CHR(13)
     MsgStop(cTexto)
	 //lRet := .F.
     //Return(lRet)
EndIf

If !(SC6->(FieldPos("C6_CARGA")) > 0 ) //se nao existir
     cTexto += "O campo C6_CARGA não existe na base. Acionar Suporte." + CHR(13)
	 //cTexto += "O processo não será concluído." + CHR(13)
     MsgStop(cTexto)
	 //lRet := .F.
     //Return(lRet)
EndIf

If (SC9->(FieldPos("C9_CARGA")) > 0 ) .AND. (SC6->(FieldPos("C6_CARGA")) > 0 ) //se existir o campo
	cQuery    := "SELECT C6_FILIAL,C6_NUM,C6_ITEM,RTRIM(C6_PRODUTO)C6_PRODUTO,C6_CARGA "
	cQuery    += "FROM "+RetSqlName("SC6")+" SC6 "
	cQuery    += "WHERE C6_FILIAL = '"+xFilial("SC6")+"' AND C6_NUM = '"+SC5->C5_NUM+"' "
	cQuery    += "AND SC6.D_E_L_E_T_ <> '*'  "
	cQuery    += "ORDER BY C6_FILIAL,C6_NUM,C6_ITEM,C6_CARGA "

	TcQuery cQuery Alias "TSC6" NEW

	DbSelectArea("TSC6")
	TSC6->(DbGoTop())
	While TSC6->(!EOF())

			// ATUALIZA NA SC9
			cSqlUpd := ""
			cSqlUpd += CHR(13) + "UPDATE "+RetSQLName("SC9")+" SET C9_CARGA = '"+TSC6->C6_CARGA+"' " 
			cSqlUpd += CHR(13) + "WHERE C9_FILIAL = '"+xFilial("SC9")+"' "
			cSqlUpd += CHR(13) + "AND C9_PEDIDO = '"+TSC6->C6_NUM+"' "
			cSqlUpd += CHR(13) + "AND C9_ITEM = '"+TSC6->C6_ITEM+"' "
			cSqlUpd += CHR(13) + "AND C9_PRODUTO = '"+TSC6->C6_PRODUTO+"' "
			cSqlUpd += CHR(13) + "AND C9_CARGA = ' ' "
			cSqlUpd += CHR(13) + "AND D_E_L_E_T_ <> '*' "

			nRetSQL := TcSqlExec(cSqlUpd)
			If nRetSQL < 0  // -1 se erro
				ApMsgInfo("Erro ao gravar a carga "+TSC6->C6_CARGA+" na SC9","M410PVNF()")
				//lRet := .F.
			EndIf
			cSqlUpd := ""
			
		TSC6->(dbSkip())
	EndDo
	TSC6->(dbCloseArea())
EndIf
//ApMsgInfo("passou aqui M410PVNF pedido " + SC5->C5_NUM ,"M410PVNF()")
//lRet := U_BLOQ_FAT(SC5->C5_NUM)

Return(lRet)
