#include 'totvs.ch'
/*/
-> ADVPL TRADICIONAL (ADVANCED PROTHEUS LANGUAGE)
    - LINGUAGEM PROPRIETARIA DA TOTVS PARA O ERP TOTVS PROTHEUS
    - BASEADA EM CLIPER
    - AMPLAMENTE UTILIZADA NA CONSTRU«√O DE TELAS, PONTOS DE ENTRADA, RELAT”RIOS, ENTRE OUTROS
    - OS CODIGOS PODEM SER ESCRITOS DE FORMA PROCEDURAL OU BASEADO EM ORIENTA«√O A OBJETOS
    - FRACAMENTE TIPADA
    - POSSUI LIMITACOES QUANTO A QUANTIDADE DE CARACTERES QUE COMPOE NOMES DE VARIAVEIS E FUNCOES
    - AINDA DOMINANTE NO ANO DE 2023
    - MSEXECAUTO() RESPONSAVEL PELA EXECUCAO DE PROGRAMAS DE FORMA AUTOM¡TICA

-> ADVPL MVC (MODEL VIEW CONTROL)
    - ATUALIZA«√O DA LINGUAGEM ADVPL TRADICIONAL PARA CONSTRU«√O DE APLICA«’ES BASEADAS NA ARQUITETURA MVC
    - SEPARA A APLICA«√O EM DIFERENTES PARTES QUE SEGUEM UM MODELO PADRAO DEFINIDO
    - OS COMPONENTES DESSE MODELO PODEM OU NAO FAZER PARTE DO MESMO ARQUIVO DE CODIGO FONTE
    - A ESTRUTURA DE UM PROGRAMA EM ADVPL MVC POSSUI OS SEGUINTES COMPONENTES:
        -> FUNCAO PRINCIPAL RESPONSAVEL PELO COMPONENTE BROWSE
        -> FUNCAO STATIC NOMEADA COMO MENUDEF, ONDE … DEFINIDA A ESTRUTURA DO MENU
        -> FUNCAO STATIC NOMEADA COMO VIEWDEF, ONDE … CONSTRUÕDA A L”GICA DE IMPLEMENTA«√O DA INTERFACE GRAFICA
        -> FUNCAO STATIC NOMEADA COMO MODELDEF, ONDE … CONSTRUÕDA A L”GICA DAS REGRAS DA APLICACAO
        -> PODE POSSUIR FUNCOES ADICIONAIS DE APOIO ¿S REGRAS DA MODELDEF
    - MUDAN√áA NA LOGICA DE IMPLEMENTA«√O DE PONTOS DE ENTRADA
    - MUDAN√áA NO CONCEITO DE ROTINAS AUTOM¡TICAS

-> TOTVS LANGUAGE PLUS PLUS (TLPP)
    - EVOLUCAO DA LINGUAGEM ADVPL TRACIONAL
    - ADICIONA NOVOS RECURSOS ¿ LINGUAGEM
    - A DECLARACAO DE FUN«’ES, VARI¡VEIS, ATRIBUTOS DE CLASSES E M…TODOS PASSA A PODER SER TIPADA DE FORMA
        EXPLICITA
    - POSSUI TRATAMENTOS EM TEMPO DE COMPILA«√O PARA PREVEN«√O DE ERROS
    - N√ÉO … COMPATIVEL COM ADVPL MVC            
/*/
