IIF((!SE2->E2_PREFIXO$"ADV|VIG|INC").AND.SE5->E5_MOTBX=="DEB".AND.SE5->E5_TIPODOC=="VL".AND.SE5->E5_RECPAG=="P",SE5->(E5_VALOR-E5_VLJUROS-E5_VLMULTA),IIF(SE2->E2_PREFIXO=="INC",SEV->EV_VALOR,0))   
IIF((!SE2->E2_PREFIXO$"ADV|VIG|INC").AND.SE5->E5_MOTBX=="DEB".AND.SE5->E5_TIPODOC=="VL".AND.SE5->E5_RECPAG=="P",SE5->E5_VALOR,IIF(SE2->E2_PREFIXO=="INC",SEV->EV_VALOR,0))          

IIF((!SE2->E2_PREFIXO$"ADV|VIG").AND.SE5->E5_MOTBX=="DEB".AND.SE5->E5_TIPODOC=="VL".AND.SE5->E5_RECPAG=="P",SE5->(E5_VALOR-E5_VLJUROS-E5_VLMULTA),0)   
IIF((!SE2->E2_PREFIXO$"ADV|VIG").AND.SE5->E5_MOTBX=="DEB".AND.SE5->E5_TIPODOC=="VL".AND.SE5->E5_RECPAG=="P",SE5->E5_VALOR,0)     
