#include "totvs.ch"
#include "tlpp-core.th"
#include "tlpp-object.th"

/*/{Protheus.doc} IMPORTAR_DADOS_CSV
    Teste prático de importação, leitura e gravação de registros em arquivos CSV para o ambiente Protheus.
    @type  Function
    @author Carlos Batista
    /*/
#define DRIVE "C:\"

user function IMPORTAR_DADOS_CSV_1

    Local cArquivo  as character
    Local cBuffer   as character
    Local cTexto    as character
    local cDrive   := DRIVE as character
    Local nHandle   as numeric
    Local nTamFile  as numeric
    Local nTamLidos as numeric
    Local aLinhas   as array
    Local aDados    as array

    rpcSetEnv('99','01')
    

    cArquivo := tFileDialog( "All files (*.csv) | All Text files (*.csv)",;
                            "Selecao de Arquivos",,cDrive, .f.)

    nHandle  := fOpen(cArquivo)

    IF nHandle < 0
        fwAlertError("ERRO AO EFETUAR A LEITURA DO ARQUIVO - CODIGO DE ERRO: " + str(fError(),4))
        rpcClearEnv()
        return .F.
    EndIF 

    nTamFile := fSeek(nHandle,0,2)   
    fSeek(nHandle,0)

    While nTamLidos < nTamFile
        cBuffer := ''
        nTamLidos += fRead(nHandle,@cBuffer,500)
        cTexto  += cBuffer
    Enddo

    fClose(nHandle)

    aDados  := array(0)
    aLinhas := strToKArr(cTexto,CHR(13) + CHR(10))
    aEval(aLinhas,{|x| aadd(aDados,strToKArr(x,";"))})

    rpcClearEnv()
    
Return 
